baseURL = "https://blog.mywebofthings.com"
title = "Minimo"

theme = "minimo"

googleAnalytics = ""
Paginate = 3

[params]
  description = "Minimalist theme for Hugo"
  dateFormat = "2 Jan 2006"
  copyrightOwner = "Roberto Migli"
  copyrightStartYear = "2017"
  hideSingleNavigation = true

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "Roberto Migli"

[author.social]
  github = "sybeck2k"
  twitter = "LuominLi"

[permalinks]
  page = "/:slug/"

[[menu.main]]
  name = "Home"
  weight = -70
  identifier = "home"
  url = "https://blog.mywebofthings.com"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
