baseURL = "https://blog.mywebofthings.com"
title = "A blog of tech"

theme = "coco"

googleAnalytics = "UA-100840815-1"
Paginate = 3

pygmentsuseclasses  = true
disqusshortname     = "mywebofthings"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "About"
weight                 = -110
identifier             = "about"
url                    = "/about/"

[params]
  dateForm = "2 Jan 2006"
  copyrightOwner = "Roberto Migli"
  copyrightStartYear = "2017"
  hideSingleNavigation = true
  highlightjs            = true
  linkedin               = "//linkedin.com/in/robertomigli"
  github                 = "//github.com/sybeck2k"
  twitter                = "//twitter.com/luominli"
  selfintro              = "Ideas, thoughts and rants about code and systems"  
  highlightjsStyle       = "darcula"
  avatar                 = "img/profile.png"
  author = "Roberto Migli"

[taxonomies]
  category = "categories"
  tag = "tags"

[author]
  name = "Roberto Migli"

[[menu.main]]
  name = "Home"
  weight = -70
  identifier = "home"
  url = "https://blog.mywebofthings.com"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1