baseURL = "https://blog.mywebofthings.com/"
title = "A blog of tech"

languageCode = "en-us"

theme = "bootstrap"
# number of posts to show on home/category/tag pages (Default: 10)
paginate = 5

# optionally override the site's footer with custom copyright text
copyright = "Except where otherwise noted, content on this site is licensed under a [Creative Commons Attribution 4.0 International license](https://creativecommons.org/licenses/by-sa/4.0/)."
googleAnalytics = "UA-100840815-1"
disqusshortname = "mywebofthings"

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[[menu.navbar]]
  name = "About"
  url = "/about/"

# Theme variables
#
[params]
  # Site author
  author = "Roberto Migli"

  # Description/subtitle for homepage (can be Markdown)
  description = "Ideas, thoughts and rants about code and systems"

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  # Optionally display a message about the site's use of cookies, which may be
  # required for your site in the European Union. Set the parameter below to a
  # page where the user can get more information about cookies, either on your
  # site or externally, for example:
  #cookie_consent_info_url = "/cookie-information/"
  #cookie_consent_info_url = "http://cookiesandyou.com"

  custom_navbar = true
  #sharingicons = true

  # Display post summaries instead of content in list templates (default: true)
  #truncate = true

  # Disable the use of sub-resource integrity on CSS/JS assets (default: false)
  # Useful if you're using a CDN or other host where you can't control cache headers
  #disable_sri = false

  [params.sidebar]
    # Optional about block for sidebar (can be Markdown)
    # about = "A simple Hugo theme based on the [Bootstrap v4 blog example](http://v4-alpha.getbootstrap.com/examples/blog/)."

    # How many posts to show on the sidebar (Default: 5)
    num_recent_posts = 5

  [params.social]
    linkedin               = "robertomigli"
    github                 = "sybeck2k"
    twitter                = "luominli"

# Default content language for Hugo 0.17's multilingual support (default is "en")
# See: https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md
#DefaultContentLanguage = "en"

# Languages to render
#[languages.en]
#[languages.bg]

# vim: ts=2 sw=2 et
